version: '3.7'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      POSTGRES_USER: fetcher
      POSTGRES_PASSWORD: fetcher_password
      POSTGRES_DB: fetcher_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
    data: